language: java
dist: trusty
jdk:
  - oraclejdk8
git:
  submodules: true
before_install:
  - git config --global user.email "travis-ci@travis-ci.com"
  - git config --global user.name "Travis CI"
  - ./lightpaper up && ./lightpaper patch
cache:
  directories:
    - '$HOME/.m2/repository'
